FROM golang:1.22.0-alpine AS builder

WORKDIR /go/src/github.com/rem1niscence/mapreduce
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -o bin ./cmd/coordinator/*.go

FROM alpine:3.20.2
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
WORKDIR /app
COPY --from=builder /go/src/github.com/rem1niscence/mapreduce/bin ./
USER appuser
ENTRYPOINT ["/app/bin"]
